AWSTemplateFormatVersion: 2010-09-09
Description: test

Resources:
  eventbridgerulecentralaccount:
    Type: AWS::Events::Rule
    Properties:
      Description: Forward event to HealthEventBus
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
        - custom.dingtalkevent.test
      Targets:
      - Arn: "arn:aws:events:ap-southeast-1:894855526703:event-bus/HealthEventBus"
        Id: dingtalk-eventbus-account
        RoleArn:
          Fn::GetAtt:
          - EventBridgeIAMrole
          - Arn
  EventBridgeIAMrole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              Fn::Sub: events.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: PutEventsDestinationBus
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - events:PutEvents
            Resource:
            - "arn:aws:events:ap-southeast-1:894855526703:event-bus/HealthEventBus"
